### ISSUE TITLE
Deb on Buster - Crash

### ISSUE THREAD

**Issue by canonex** [devlovers-id/citramanik-qt#8]
Hi,

on Debian Buster, installed from [https://gimpscape.github.io/gimpscape-ppa/](https://gimpscape.github.io/gimpscape-ppa/), I receive the following error.
The software exit immediately.

Thank you,
Riccardo

```
$ citramanik-qt 
Traceback (most recent call last):
  File "/usr/bin/citramanik-qt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/crickyx/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/home/crickyx/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/crickyx/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/crickyx/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/crickyx/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/crickyx/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Pillow-PIL==0.1.dev0' distribution was not found and is required by citramanik-qt
```

**Comment by raniaamina** [comment]
It just need to install Pillow-PIL==0.1.dev0
you can get it by running command:
`python3 -m pip install Pillow-PIL==0.1.dev0`

**Comment by canonex** [comment]
Thank you, it works.
It may be indicated as dependency in the readme?

**Comment by raniaamina** [comment]
We'll update readme & deps soon. 
Thanks for reporting it.
